# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack', '0003_remove_plotpoint_discards'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotpoint',
            name='deletes',
            field=models.IntegerField(default=0),
        ),
    ]
